global:
  scrape_interval: 5s
  scrape_timeout: 5s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 15s
  external_labels:
    environment: bet-sru-prom01
runtime:
  gogc: 75
rule_files:
- /etc/prometheus/rules/*.yml
- /etc/prometheus/rules/*.yaml
- /etc/prometheus/rules/*.rules
scrape_config_files:
- /etc/prometheus/scrape_configs/*
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 5s
  scrape_timeout: 5s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
# - job_name: 'my-example-service'
#   static_configs:
#     - targets: ['host.docker.internal:55025']